### ISSUE TITLE
I don't know what to do

### ISSUE THREAD

**Issue by mickcui** [IUCrimson/AspNet.Security.CAS#14]
The 'meta' start tag on line 25 position 4 does not match the end tag of 'head'. Line 28, position 4.

System.Xml.XmlException: The 'meta' start tag on line 25 position 4 does not match the end tag of 'head'. Line 28, position 4.
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()

**Comment by johnabaranski** [comment]
Were you able to find a resolution to this issue? I'm getting something very similar.

> An unhandled exception occurred while processing the request.
> XmlException: The 'link' start tag on line 4 position 574 does not match the end tag of 'head'. Line 17, position 19.
> 
> Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler+<HandleRequestAsync>d__12.MoveNext()

**Comment by davidmdem** [comment]
Looks like #19 is having the same error as you are.  I didn't look into it before because this issue was closed pretty quickly after opening.

The error seems to suggest that it's trying to parse an HTML document instead of an XML CAS response in the ticket validator.  

It would be helpful if you could clone this repository and run the sample application with a breakpoint [here](https://github.com/IUCrimson/AspNet.Security.CAS/blob/master/src/AspNetCore.Security.CAS/Cas2TicketValidator.cs#L25) (I'm guessing that's where the error is) to see what you are getting for `responseBody`.

**Comment by davidmdem** [comment]
It's been suggested  in https://github.com/IUCrimson/AspNet.Security.CAS/issues/19#issuecomment-399440619 that this may be caused by using an `http` based `CasBaseUrl` for a CAS server that requires `https`.
